  name: Java CI
  on:
    - push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.HEXLET_LVL2_ID}}
          JACOCO_SOURCE_PATH: "/src/main/java"
        with:
            coverageCommand: make install
            coverageLocations: /build/reports/jacoco/test/html/jacocoTestReport.xml:jacoco
            debug: true