  name: Java CI
  on:
    push:
      branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build, Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.HEXLET_ID }}
          JACOCO_SOURCE_PATH: "/src/main/java"
        with:
            coverageCommand: make install
            coverageLocations: /build/reports/jacoco/test/html/jacocoTestReport.xml:jacoco
            debug: true